spring.application.name: entity-service

spring.rsocket.server.transport: websocket
spring.rsocket.server.mapping-path: /rsocket

APP_REDIS_HOST: localhost
APP_REDIS_PORT: 6379

# =============== grpc ===============
grpc:
  port: 6565
  enableReflection: true

spring:

management.endpoints.web.exposure.include: prometheus,health,info,metrics
