/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

import org.sonarqube.gradle.SonarQubeTask
import de.gliderpilot.gradle.semanticrelease.GithubRepo
import de.gliderpilot.gradle.semanticrelease.SemanticReleaseChangeLogService
import org.ajoberstar.gradle.git.release.semver.ChangeScope
//import pl.allegro.tech.build.axion.release.domain.TagNameSerializationConfig
import java.text.SimpleDateFormat
import java.util.*

val jacocoVersion: String by project
val jacocoQualityGate: String by project
val gcloudProject: String by project

plugins {
    id("idea")
    id("application") // implicit `java`

    id("maven-publish")

    // code coverage
    id("jacoco")
    // code quality
    id("org.sonarqube") version "2.6.2"

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.61"

    // Keep dependencies up to date
    // gradle dependencyUpdates -Drevision=release
    id("com.github.ben-manes.versions") version "0.27.0"

    // Versioning & Release with git tags
    // gradle currentVersion
    // gradle release
//    id("pl.allegro.tech.build.axion-release") version "1.10.3"
    id("de.gliderpilot.semantic-release") version "1.4.0"

    // Generate changelog
    // gradle changelogPush
//    id("com.diffplug.spotless-changelog") version "1.1.0"

    // Build & Publish docker images
    // gradle jib
    id("com.google.cloud.tools.jib") version "1.8.0"
}


//region CLI switches
val ENABLE_PODMAN = "enable-podman"
//region Properties
val enablePodman by extra(
        if (project.hasProperty(ENABLE_PODMAN))
            "true" == project.property(ENABLE_PODMAN)
        else true)





release {
    // versionStrategy  org.ajoberstar.gradle.git.release.semver.RebuildVersionStrategy.INSTANCE
}



val ghToken: String = if (project.hasProperty("smokeTests")) project.property("smokeTests").toString() else System.getenv("GH_TOKEN") ?: ""

semanticRelease {
    changeLog(closureOf<SemanticReleaseChangeLogService> {
        repo(closureOf<GithubRepo> {
            setGhToken(ghToken)
        })

//        changeScope = KotlinClosure1<org.ajoberstar.grgit.Commit, ChangeScope>({
//            val version = extractVersion()
//            when (version?.toUpperCase()) {
//                "MAJOR" -> ChangeScope.MAJOR
//                "MINOR" -> ChangeScope.MINOR
//                "PATCH" -> ChangeScope.PATCH
//                else -> null
//            }
//        })
    })

}

//scmVersion {
//    useHighestVersion = true
//
//    tag(closureOf<TagNameSerializationConfig> {
//        prefix = "" // 'v'
//        versionSeparator = ""
//    })
//
//    branchVersionIncrementer = mapOf(
//            "feature/.*" to "incrementMinor",
//            "hotfix/.*" to "incrementPatch",
//            "release/.*" to "incrementPrerelease",
//            "develop" to "incrementPatch",
//            "master" to "incrementMinor"
//    )
//}

allprojects {
//    version = scmVersion.version

    if (!project.hasProperty("release.quiet")) {
//        println("Version: $version,  Branch: ${scmVersion.scmPosition.branch}")
    }
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

configurations {
    register("bom")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

jacoco {
    toolVersion = jacocoVersion
}

sonarqube {
    properties {
        property("sonar.jacoco.reportPaths", "$buildDir/jacoco/test.exec")
        property("sonar.junit.reportPaths", "$buildDir/test-results")
        property("sonar.java.codeCoveragePlugin", "jacoco")
    }
    tasks.sonarqube {
        dependsOn("jacocoTestReport")
    }
}

publishing {
    publications {
        create<MavenPublication>("nexus") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            val releasesRepoUrl = "$buildDir/repos/releases"
            val snapshotsRepoUrl = "$buildDir/repos/snapshots"
            url = if (version.toString().endsWith("-SNAPSHOT")) uri(snapshotsRepoUrl) else uri(releasesRepoUrl)
        }
    }
}

//spotlessChangelog {
//    // only necessary if you need to change the defaults below
//    changelogFile("CHANGELOG.md")
//    enforceCheck(true)
//    branch("develop")
//    commitMessage("Published {{version}}")
//    tagPrefix("")
//}



java {
    // Java 8 needed as Beam doesn't yet support 11
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

application {
    // Define the main class for the application.
    mainClassName = "java.gitops.AppKt"
}

jib {
    setAllowInsecureRegistries(true)
    to {
        image = "xmlking/${rootProject.name}-${project.name}:${project.version}"
        // image = "gcr.io/${gcloudProject}/${rootProject.name}/${project.name}:${project.version}"

        /**
        gcr: Google Container Registry (GCR)
        osxkeychain: Docker Hub
         */
        credHelper = "osxkeychain"
        /**
        auth {
        username = "*******"
        password = "*******"
        }
         */
    }
    container {
        jvmFlags = listOf("-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-server")
        useCurrentTimestamp = true
        mainClass = application.mainClassName
        ports = listOf("8080", "8443")
    }
}

tasks {

    jacocoTestReport {
        reports {
            html.isEnabled = true
            xml.isEnabled = true
        }
    }

    jacocoTestCoverageVerification {
        violationRules {
            rule { limit { minimum = jacocoQualityGate.toBigDecimal() } }
        }
    }

    test {
        finalizedBy("jacocoTestReport")
    }

    check {
        dependsOn("jacocoTestCoverageVerification")
        dependsOn("jacocoTestReport")
    }

    withType<SonarQubeTask> {
        group = "Verification"
        dependsOn("check")
    }

    fun isNonStable(version: String): Boolean {
        val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { version.toUpperCase().contains(it) }
        val regex = "^[0-9,.v-]+(-r)?$".toRegex()
        val isStable = stableKeyword || regex.matches(version)
        return isStable.not()
    }

    dependencyUpdates {
        rejectVersionIf {
            isNonStable(candidate.version)
        }

        // optional parameters
        outputDir = "$buildDir/dependencyUpdates"
        checkForGradleUpdate = true
        revision = "release"
        gradleReleaseChannel = "current"
    }

    jar {
        val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
        sdf.timeZone = TimeZone.getTimeZone("UTC");

        manifest.attributes.apply {
            put("Build-By", System.getProperty("user.name"))
            put("Build-Date", sdf.format(Date()))
            put("Build-JDK", org.gradle.internal.jvm.Jvm.current())
//            put("Build-Revision", scmVersion.scmPosition.shortRevision)
            // put("Build-Revision",ve)
            put("Specification-Title", project.name)
            put("Specification-Version", project.version)
            put("Specification-Vendor", project.group)
            put("Implementation-Title", project.name)
            put("Implementation-Version", project.version)
            put("Implementation-Vendor", project.group)
        }
    }

}


fun org.ajoberstar.grgit.Commit.extractVersion(): String? {
    val open = fullMessage.indexOf("[")
    val close = fullMessage.indexOf("]")

    if (open < 0 || close < 0) {
        return null
    }

    return fullMessage.subSequence(open + 1, close).toString()
}

fun Project.isSnapshot() = version.toString().contains("SNAPSHOT")
