version: "3.9"

services:

  mssql:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    platform: linux/amd64
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
