version: "3.9"

services:

  redis:
    image: redislabs/redismod:edge
    environment:
      # make a test user and database
      - REDIS_PASSWORD=redis
      # redis rdb backup config.
      # Save if 100 keys are added in every 10 seconds: --save 10 100
      - "REDIS_ARGS=--appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  insight:
    image: redislabs/redisinsight:1.13.1
    ports:
      - '8001:8001'
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - redisinsight:/db

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_INSTALL_PLUGINS=redis-datasource,redis-app
      # defend following secrets in .env and don't commit `.env` file to git.
      - REDIS_CLOUD_HOST
      - REDIS_CLOUD_PASSWORD
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - grafana:/var/lib/grafana
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redisdata:
  redisinsight:
  grafana:
