version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    networks:
      - redpanda_network
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr redpanda:8082
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
      - --set redpanda.auto_create_topics_enabled=true
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    healthcheck:
      test: "curl -f localhost:9644/v1/status/ready"
      interval: 3s
      start_period: 30s
    volumes:
      - redpanda:/var/lib/redpanda/data

  connect:
    image: redpandadata/connectors:latest
    hostname: connect
    container_name: connect
    networks:
      - redpanda_network
    # comment `platform` if you are using windows or intel mac.
    platform: 'linux/amd64'
    environment:
      CONNECT_CONFIGURATION: |
        key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
        value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
        group.id=connectors-cluster
        offset.storage.topic=_internal_connectors_offsets
        config.storage.topic=_internal_connectors_configs
        status.storage.topic=_internal_connectors_status
        config.storage.replication.factor=-1
        offset.storage.replication.factor=-1
        status.storage.replication.factor=-1
        offset.flush.interval.ms=1000
        producer.linger.ms=50
        producer.batch.size=131072
      CONNECT_BOOTSTRAP_SERVERS: redpanda:29092
      CONNECT_GC_LOG_ENABLED: "false"
      CONNECT_HEAP_OPTS: -Xms512M -Xmx512M
      CONNECT_LOG_LEVEL: info
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      redpanda:
        condition: service_healthy

  console:
    image: redpandadata/console:v2.2.3
    hostname: console
    container_name: console
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: ksql-connect-cluster
              url: "http://ksqldb:8083"
#          clusters:
#            - name: local-connect-cluster
#              url: "http://connect:8083"
    ports:
      - 9090:8080
    depends_on:
      redpanda:
        condition: service_healthy
      connect:
        condition: service_healthy
      ksqldb:
        condition: service_healthy



# Ref: https://github.com/geoHeil/streaming-example/blob/master/docker-compose.yml
# Ref: https://redpanda.com/blog/ksqldb-materialized-cache
  ksqldb:
    image: confluentinc/ksqldb-server:0.28.2
    hostname: ksqldb
    container_name: ksqldb
    networks:
      - redpanda_network
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8088:8088"
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/healthcheck"]
      interval: 45s
      timeout: 15s
      retries: 5
    # comment `platform` if you are using windows or intel mac.
    platform: 'linux/amd64'
    volumes:
      - "./kafka/plugins/:/usr/share/kafka/plugins/"
#      - /kafka/connectors/confluentinc-kafka-connect-elasticsearch:/opt/kafka/redpanda-plugins/confluentinc-kafka-connect-elasticsearch
#      - /kafka/connectors/confluentinc-kafka-connect-datagen:/opt/kafka/redpanda-plugins/confluentinc-kafka-connect-datagen
#      - /kafka/connectors/confluentinc-kafka-connect-s3:/opt/kafka/redpanda-plugins/confluentinc-kafka-connect-s3
    environment:
      KSQL_HOST_NAME: "event-mesh"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_KSQL_ADVERTISED_LISTENER: http://ksqldb:8088
      KSQL_BOOTSTRAP_SERVERS: "redpanda:29092"
      KSQL_KSQL_STREAMS_BOOTSTRAP_SERVERS: "redpanda:29092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://redpanda:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      # Configuration to embed Kafka Connect support.
      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: 'ksqldb'
      KSQL_CONNECT_REST_PORT: 8083
      KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: "redpanda:29092"
      KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://redpanda:8081"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://redpanda:8081"
#      KSQL_KSQL_PERSISTENCE_DEFAULT_FORMAT_KEY: AVRO
#      KSQL_KSQL_PERSISTENCE_DEFAULT_FORMAT_VALUE: AVRO
#      KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
#      KSQL_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
#      KSQL_CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
#      KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
#      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      KSQL_KSQL_HEARTBEAT_ENABLE: 'false'
#      KSQL_KSQL_STREAMS_NUM_STANDBY_REPLICAS: 1
#      KSQL_KSQL_QUERY_PULL_ENABLE_STANDBY_READS: 'true'
#      KSQL_LOG4J_ROOT_LOGLEVEL: "ERROR"
#      KSQL_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
#      KSQL_LOG4J_PROCESSING_LOG_BROKERLIST: kafka:29092
#      KSQL_LOG4J_PROCESSING_LOG_TOPIC: <ksql-processing-log-topic-name>
#      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_NAME: <ksql-processing-log-topic-name>
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "_ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "_ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "_ksql-connect-statuses"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_PLUGIN_PATH: "/usr/share/kafka/plugins"
    restart: unless-stopped
#    depends_on:
#      redpanda:
#        condition: service_healthy
#      connect:
#        condition: service_healthy

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.28.2
    container_name: ksqldb-cli
    # comment `platform` if you are using windows or intel mac.
    platform: 'linux/amd64'
    entrypoint: /bin/sh
    tty: true
    volumes:
      - ./kafka/sql:/etc/sql
#    depends_on:
#      redpanda:
#        condition: service_healthy
#      ksqldb:
#        condition: service_healthy

  kafdrop:
    image: obsidiandynamics/kafdrop:3.31.0
    hostname: kafdrop
    container_name: kafdrop
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKERCONNECT=redpanda:9092
      - JVM_OPTS=-Xms32M -Xms64M
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - "9000:9000"
    depends_on:
      redpanda:
        condition: service_healthy
      ksqldb:
        condition: service_healthy
    healthcheck:
      test: "curl -f kafdrop:9000/actuator/health || exit 1"
      start_period: 30s

  materialized:
    image: materialize/materialized:latest
    container_name: materialized
    command: -w2 --disable-telemetry
    ports:
      - 6875:6875
  mzcli:
    image: materialize/cli:latest
    container_name: mzcli
    init: true
    tty: true
    depends_on:
      - materialized
  metabase:
    image: metabase/metabase:v0.46.1
    container_name: metabase
    depends_on:
      - materialized
    ports:
      - 3030:3000

networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda: null
