spring.application.name: entity-service

spring.rsocket.server.transport: websocket
spring.rsocket.server.mapping-path: /rsocket

APP_REDIS_HOST: localhost
APP_REDIS_PORT: 6379

# disable GCP for local dev
spring.cloud.gcp.core.enabled: false
management.metrics.export.stackdriver.enabled: false

# ==== application properties  ========
features:
  change-events:
    enabled: true

# =============== server ===============
server:
  shutdown: graceful

# =============== management ===============
management.endpoints.web.exposure.include: prometheus,health,info,metrics

# =============== spring ===============
spring:

# =============== redis ===============
  redis:
#    cluster:
#      nodes:
#    url: redis://localhost:6379
    host: '${APP_REDIS_HOST}'
    port: '${APP_REDIS_PORT}'
    password: redis
    database: 0
    timeout: 100
    lettuce:
      shutdown-timeout: PT0S
      pool:
        max-active: 8
        max-wait: PT10S
        max-idle: 8
        min-idle: 1
