/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package micro.apps.shared.dsl

import kotlin.test.Test
import kotlin.test.assertTrue

class KBeamDSLTest {
    @Test fun testKBeamDsl() {
        assertTrue(true)
    }
}
