server:
  shutdown: graceful
# ==================== logging ============================
logging:
  level:
    micro.apps.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
# ==================== management ==========================
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
# ==================== spring ==============================
spring:
  config:
    import: optional:file:.env[.properties]
  graphql:
    path: /graphql
    websocket:
      path: /graphql
    schema:
      printer:
        enabled: true
      introspection:
        enabled: false
      locations:
        - classpath*:graphql/**/
    graphiql:
      enabled: true
#    cors:
#      allowed-origins: '*'
#      allowed-headers: '*'
#      allowed-methods: '*'

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    username: user
    password: password
  devtools:
    livereload:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: https://accounts.google.com
          # jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          # public-key-location: classpath:my-key.pub
          jws-algorithms: [HS256,RS256]
          audiences: hasura
  flyway:
    baseline-on-migrate: true
    # default-schema: public
# ==================== application properties  =============
feature:
  postMvp:
    enabled: false
security:
  jwt:
    signing-key: ${JWT_SIGNING_KEY}
  users:
    basic-auth:
      - username: "user"
        password: "resu"
        authorities:
          - "SCOPE_GRAPHQL"
          - "SCOPE_viewer"
      - username: "admin"
        password: "nimda"
        authorities:
          - "SCOPE_GRAPHQL"
          - "SCOPE_GRAPHIQL"
          - "SCOPE_H2"
          - "SCOPE_editor"
          - "SCOPE_moderator"
      - username: "actuator"
        password: "rotautca"
        authorities:
          - "SCOPE_ACTUATOR"
