apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        #prometheus.io/port: "3101"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: service
          image: xmlking/spring-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-vars
            - configMapRef:
                name: env-vars-common
            - secretRef:
                name: secrets
