apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  # We want the servers to become available even if they're not ready
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8080
      targetPort: http
