debug: false
# ==================== spring ==============================
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
# ==================== application properties  =============
application:
  runner:
    enabled: false
