version_info: '0'
resources:
  - "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
    cluster_name: echo_service2
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: { address: 192.168.2.244, port_value: 5001 }
