spring.application.name: entity-service

spring.rsocket.server.transport: websocket
spring.rsocket.server.mapping-path: /rsocket

# ==== application properties  ========
#features:
#  change-events:
#    enabled: true

# =============== grpc ===============
grpc:
  port: 6565
  enableReflection: true

# =============== server ===============
server:
  shutdown: graceful # also set `timeout-per-shutdown-phase`

# =============== management ===============
management.endpoints.web.exposure.include: prometheus,health,info,metrics

# =============== spring ===============
spring:

  lifecycle:
    timeout-per-shutdown-phase: "10s"
