name: Deploy
on:
  release:
    types: [ published ]

env:
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
#jobs:
#  BINTRAY_UPLOAD:
#    name: Bintray Upload
#    runs-on: ubuntu-latest
#    env:
#      TRAVIS: true
#      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'zulu'
#      - name: Perform bintray upload
#        run: ./gradlew bintrayUpload
